# Changes here will be overwritten by Copier
_commit: 1.5.7
_src_path: https://github.com/pawamoy/copier-uv.git
author_email: vandy.goel23@gmail.com
author_fullname: vandyG
author_username: vandyG
copyright_date: '2025'
copyright_holder: vandyG
copyright_holder_email: vandy.goel23@gmail.com
copyright_license: MIT License
insiders: false
project_description: Who Wants to be a Millionaire?
project_name: wwtbm
python_package_command_line_name: wwtbm
python_package_distribution_name: wwtbm
python_package_import_name: wwtbm
repository_name: wwtbm
repository_namespace: vandyG
repository_provider: github.com

